MPRSA_MOD_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(MPRSA_MOD_DIR)/mprsa.c
SRC_USERMOD += $(MPRSA_MOD_DIR)/tfm/tfm_mpi.c

CFLAGS_USERMOD += -I$(MPRSA_MOD_DIR)
CFLAGS_USERMOD += -DMICROPY_PY_MPRSA=1
